# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather' do
  use_frameworks!
  pod 'SwiftKeychainWrapper'

  target 'WeatherTests' do
    inherit! :search_paths

  end

  target 'WeatherUITests' do
   
  end

end
